"""Vault structure creation and management."""

from pathlib import Path

from .config import (
    RAW_SOURCES_DIR,
    SCRATCH_DIR,
    VAULT_ROOT,
    WIKI_DIR,
)

CLAUDE_MD_TEMPLATE = """\
# Kenyon Confidential Bot — Wiki Schema

## Identity
You are the Kenyon Confidential Bot. You give personalized, helpful academic
advice to Kenyon College students using ONLY the knowledge in 01-Wiki/ and
02-Scratch-Memory/. Always cite sources. Always use [[wiki-links]] for
cross-references.

## Vault Structure
- 00-Raw-Sources/ — IMMUTABLE. Never write here. This is the raw scraped data.
- 01-Wiki/ — YOUR workspace. Create and maintain structured Markdown pages here.
- 02-Scratch-Memory/ — YOUR memory. Health checks, advisor notes, improvement logs.

## Entity Types
Create pages in 01-Wiki/ for: Department, Course, Professor, Research, Grant,
Lab, Collaboration. Use the page template (see below).

## Page Template
Every page in 01-Wiki/ must have:
1. YAML frontmatter with: type, title, related, last_updated, sources
2. Overview section (1-2 paragraphs)
3. Details section (structured content)
4. Related section (wiki-links to 2+ related entities)
5. Advisor Notes section (personalized recommendations)

## Cross-Linking Rules
- Every page links to at least 2 related entities
- Courses → department, prerequisites, professors
- Professors → department, courses, research
- Research → faculty mentors, relevant courses

## Operations

### INGEST
When told to ingest: Read all files in 00-Raw-Sources/. For each piece of
information, create or update the appropriate entity page in 01-Wiki/.
Add cross-links. Generate index.md as a table of contents.

### QUERY
When asked a question: Search 01-Wiki/ and 02-Scratch-Memory/ for relevant
pages. Synthesize a personalized answer. Cite sources with [[wiki-links]].
Update 02-Scratch-Memory/advisor-memory.md with the interaction.

### LINT (Health Check)
When told to lint: Scan 01-Wiki/ for broken links, orphaned pages, missing
cross-references, and stale information. Fix issues. Log results in
02-Scratch-Memory/health-YYYY-MM-DD.md. Suggest improvements.
"""

INDEX_MD_TEMPLATE = """\
# Kenyon Advisor Wiki — Index

_This file will be auto-generated by the LLM during ingest._
"""


def create_vault(root: Path | None = None) -> Path:
    """Create the 3-layer vault directory structure.

    Returns the vault root path.
    """
    vault = root or VAULT_ROOT
    raw_dir = vault / RAW_SOURCES_DIR.name
    wiki_dir = vault / WIKI_DIR.name
    scratch_dir = vault / SCRATCH_DIR.name

    for d in [raw_dir, wiki_dir, scratch_dir]:
        d.mkdir(parents=True, exist_ok=True)

    claude_md = vault / "CLAUDE.md"
    if not claude_md.exists():
        claude_md.write_text(CLAUDE_MD_TEMPLATE)

    index_md = vault / "index.md"
    if not index_md.exists():
        index_md.write_text(INDEX_MD_TEMPLATE)

    return vault


def validate_vault(root: Path | None = None) -> list[str]:
    """Validate vault structure. Returns list of issues (empty = valid)."""
    vault = root or VAULT_ROOT
    issues: list[str] = []

    if not vault.exists():
        issues.append(f"Vault root does not exist: {vault}")
        return issues

    for dirname in ["00-Raw-Sources", "01-Wiki", "02-Scratch-Memory"]:
        if not (vault / dirname).is_dir():
            issues.append(f"Missing directory: {dirname}")

    if not (vault / "CLAUDE.md").is_file():
        issues.append("Missing CLAUDE.md schema file")

    if not (vault / "index.md").is_file():
        issues.append("Missing index.md")

    return issues


def get_raw_source_files(root: Path | None = None) -> list[Path]:
    """List all Markdown files in 00-Raw-Sources/."""
    vault = root or VAULT_ROOT
    raw_dir = vault / "00-Raw-Sources"
    if not raw_dir.exists():
        return []
    return sorted(raw_dir.glob("*.md"))


def save_scraped_content(filename: str, content: str, root: Path | None = None) -> Path:
    """Save scraped Markdown content to 00-Raw-Sources/.

    Returns the path to the saved file.
    """
    vault = root or VAULT_ROOT
    raw_dir = vault / "00-Raw-Sources"
    raw_dir.mkdir(parents=True, exist_ok=True)

    filepath = raw_dir / filename
    filepath.write_text(content, encoding="utf-8")
    return filepath
